#!/bin/bash
while true;do
	sleep 1
	UTIL=$(sudo cat /sys/kernel/debug/ieee80211/phy0/jychoi/chan_util)
	NUM=$(sudo cat /sys/kernel/debug/ieee80211/phy0/jychoi/chan_num)
	READY=$(sudo cat /sys/kernel/debug/ieee80211/phy0/jychoi/chan_ready)
	if [ ${READY} -eq 1 ]; then
		echo ubertooth command ${UTIL} ${NUM} ${READY}
		echo 0 > /sys/kernel/debug/ieee80211/phy0/jychoi/chan_ready
	fi
done
